### ISSUE TITLE
Crash on concurrent access of resources

### ISSUE THREAD

**Issue by mjadczak** [stripe/stripe-mock#10]
I'm using stripe-mock to run a test suite for a Stripe client library for Elixir. I only just realised that stripe-mock responds based on fixtures and does not keep internal state, and so I switched the test suite over to be asynchronous, such that many tests can execute at a time.

However, it seems that stripe-mock cannot handle concurrent access right now. [Here is the output](https://gist.github.com/mjadczak/c60ec331217551849703c0c0ea1c5511) with `-verbose` enabled. It seems to me that the internal fixture map is being accessed at the same time in an unsafe way. I'm not much of a Go programmer so I don't think I can help out much more than that.

This is probably low priority since a simple fix is to just ensure that access is serial, but allowing concurrent access would be good for running large test suites quickly.

**Comment by brandur-stripe** [comment]
Oh no! Good concurrency is the whole point of using something like Go.

Thanks for filing. It looks like the fix should be pretty straightforward. I'll look into it.

**Comment by brandur-stripe** [comment]
Alright, I've got a good handle on this problem, and am quite embarrassed at how amateur it was :) I'm going to try and write a few regression tests, but I should have a fix out by tomorrow.

**Comment by brandur-stripe** [comment]
Shipped a fixed version as 0.1.16.
