### ISSUE TITLE
Is it possible to use stripe-mock with uber-go/mock?

### ISSUE THREAD

**Issue by kakuiho** [stripe/stripe-mock#1029]
Is it possible to use stripe-mock with [uber-go/mock](https://github.com/uber-go/mock)?

pseudocode

```go
	// setup envs
	ctrl := gomock.NewController(t)
	stripeImpl := stripe.NewImplMock(ctrl)
	stripe.UseImpl(stripeImpl)

	// make up something we want 
	mockIter := ...
	stripeImpl.EXPECT().PriceList(xxx).Return(mockIter, nil)
	// or 
	// stripePriceImpl.EXPECT().List(xxx).Return(mockIter, nil)

	// testing 
	params := &stripe.PriceListParams{
		LookupKeys: stripe.StringSlice([]string{LookupKey}),
	}
	rsIter := price.List(params)
	// ...
```

**Comment by seanzhang-stripe** [comment]
`stripe-mock` is a mock HTTP server and I'm not sure if `uber-go/mock` can interact with a mock HTTP server. Anyway, `stripe-go` utilizes `stripe-mock` for testing, you can check the test code [here](https://github.com/stripe/stripe-go/blob/master/scripts/test_with_stripe_mock/main.go#L123) to see how to use it.
