### ISSUE TITLE
GET requests should not require a `Content-Type` header

### ISSUE THREAD

**Issue by ob-stripe** [stripe/stripe-mock#107]
With the latest version, sending a GET request without a `Content-Type` header fails:

```
❯ curl -v http://localhost:12111/v1/customers/cus_123 -H "Authorization: Bearer sk_test_123"
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 12111 (#0)
> GET /v1/customers/cus_123 HTTP/1.1
> Host: localhost:12111
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Bearer sk_test_123
>
< HTTP/1.1 400 Bad Request
< Request-Id: req_123
< Stripe-Mock-Version: 0.29.0
< Date: Wed, 29 Aug 2018 10:30:11 GMT
< Content-Length: 165
< Content-Type: text/plain; charset=utf-8
<
{
  "error": {
    "message": "Request's `Content-Type` header was empty. Expected: `application/x-www-form-urlencoded`.",
    "type": "invalid_request_error"
  }
}
* Connection #0 to host localhost left intact
```

The Java client library does not include a `Content-Type` header when sending GET requests, so the test suite fails with the latest version of stripe-mock.

**Comment by brandur-stripe** [comment]
Thanks for opening! I have a patch coming through that reworks a lot of this stuff and I think it'll fix this one too.

**Comment by polybuildr** [comment]
This is indeed fixed now (at least in the version I get from `go get -u github.com/stripe/stripe-mock`, so this issue can probably be closed. :)

**Comment by remi-stripe** [comment]
thanks for confirming!
