### ISSUE TITLE
Tagging releases for Docker Hub?

### ISSUE THREAD

**Issue by mcrumm** [stripe/stripe-mock#110]
First, thank you for stripe-mock!  It's unbelievably helpful.

...the v0.30.0 release broke our CI pipeline, as at least one unofficial library is not properly handling `GET` params, aside from also being pinned to `2018-05-21`. There was some mention in #50 of possibly adding tags for docker images -- is this still a possibility?

**Comment by brandur-stripe** [comment]
Sorry to hear about the trouble caused by the changes!

I just merged a patch to start [tagging on Docker Hub](https://hub.docker.com/r/stripemock/stripe-mock/tags/) and created a test release for v0.30.2 that you can lock to (provided you're able to get the incompatibilities resolved).

**Comment by mcrumm** [comment]
@brahn-stripe this is awesome!  Thanks for moving on that so quickly.
