### ISSUE TITLE
Best way to load fixtures via docker-compose.

### ISSUE THREAD

**Issue by j** [stripe/stripe-mock#122]
What's the preferred way of loading custom fixtures via docker-compose?

My api is tightly coupled with specific skus and testing makes it rough with this, so I'd like to be able to define custom fixtures.

Thanks!

**Comment by brandur-stripe** [comment]
Are you asking how you'd bundle a fixtures file and then use it with the `-fixtures` options in stripe-mock?

**Comment by j** [comment]
Yeah, I was using the stripe docker container but didn't have enough resources to keep looking up the fixtures part.  We ended up not using stripe-mock and just mocked the Node.js stripe itself for testing.

**Comment by brandur-stripe** [comment]
> We ended up not using stripe-mock and just mocked the Node.js stripe itself for testing.

Roger. In that case, I'm going to close this out. Thanks for following up!
