### ISSUE TITLE
New source of type 'three_d_secure' returns a validation error

### ISSUE THREAD

**Issue by carantunes** [stripe/stripe-mock#134]
When I create a new source of type "three_d_secure" an error is returned related to the card sent in the TypeData field.

Logs
```
Request: POST /v1/sources
Request data = map[metadata:map[booking_id:12345] amount:100 currency:eur owner:map[name:string] redirect:map[return_url:https://some-url.com] type:three_d_secure three_d_secure:map[card:card_1B3xSU2eZvKYlo2CB4hHWxFm]]
Request validation error: validator 0xc420a8cf90 failed: additional properties are not allowed: three_d_secure
```

**Comment by ob-stripe** [comment]
Hi @carantunes, thanks for the report. It seems that the `three_d_secure` parameter is not present in the public OpenAPI specification for the `POST /v1/sources` endpoint.

Note that even if we were to fix the specification to add this parameter, stripe-mock currently does not have the ability to return a resource consistent with the parameters, only with the endpoint. That is to say, stripe-mock would return a source object, but probably not one with `type=three_d_secure` (looking at the current version of the fixtures file, the `source` fixture has `type=ach_credit_transfer`).

**Comment by carantunes** [comment]
Hi, thanks for the fast answer! 

> Note that even if we were to fix the specification to add this parameter, stripe-mock currently does not have the ability to return a resource consistent with the parameters, only with the endpoint.

I know that, however for testing purposes I need the create sources endpoint to work with type=three_d_secure, even if the returned resource is not consistent with the parameter.

**Comment by pakrym-stripe** [comment]
Hi. I apologize for the extremely delayed response. The `three_d_secure` is now available in the spec.
