### ISSUE TITLE
returned `id`s are the same for every request

### ISSUE THREAD

**Issue by Tiedye** [stripe/stripe-mock#152]
Since the returned `id`s are just taken from a fixture, the same `id` is returned every time.  This causes integrity errors when testing the system I am working with

**Comment by brandur-stripe** [comment]
This should be relatively easy to fix because we've already got infrastructure for distributing IDs in a response object that were parsed out of an incoming URL. I'll take a look.

**Comment by brandur-stripe** [comment]
Took a shot at this in #153.

**Comment by Tiedye** [comment]
Once https://github.com/stripe/stripe-mock/pull/153 is merged and deployed, the stripe shim will be redundant

**Comment by brandur-stripe** [comment]
Released this feature in 0.50.0.

**Comment by Tiedye** [comment]
Wonderful!
