### ISSUE TITLE
Support for error tokens, webhooks and mocked checkout

### ISSUE THREAD

**Issue by mzdemezer** [stripe/stripe-mock#16]
I work as ruby programmer and I really like the concept of this project. It is great that an _official_ solution like this has emerged. Also, it is fantastic, that one line - changing `Stripe.api_base` - is enough to run test suite in ruby with the mock server.

However, there are some aspects that refrain me from using it for tests.

The first one is lack of support for [error tokens](https://stripe.com/docs/testing). Maybe I didn't find the proper configuration? Without proper error responses it is difficult to think of using the library in real project for tests, while with VCR it is possible to record Stripe responses in a variety of error cases simply catching tokens with debugger.

The second thing are client-side scripts. By default they call the real Stripe servers. Having a test version of js that called local mock instance would make it possible to write functional tests with Capybara, testing standard payment integration in end-to-end manner. Similar solution is implemented by [fake_stripe](https://github.com/thoughtbot/fake_stripe).

Lastly, support for webhooks would make it possible to test more complicated integrations in functional tests. It would be possible to e.g. test a whole subscription flow with first payment if the mock server sent back a request with event to the app server. I know this would either be limited to only subset of cases or bring relatively big complexity to the library. Still, it seems to me that having only the subset of the cases like creating subscription or charge would make the library more usable. Another option would be to manually trigger webhooks in a similar manner as it is done in [stripe-ruby-mock](https://github.com/rebelidealist/stripe-ruby-mock).

I am looking forward for this project to grow as, imho, there is no best option for mocking Stripe integration at the moment. Keep up the good work! :)

**Comment by brandur-stripe** [comment]
Hi Michał, thanks for trying this out and for the detailed feedback!

Unfortunately, I don't think I'm going to get to this immediately, but I agree on all counts, and our goal here will be to make stripe-mock as comprehensive as possible for the purposes of exercising a Stripe integration. For now, I'm going to label this issue with "future", and we'll circle back around when we get a chance.

**Comment by jedi1156** [comment]
Of course :)
Thank you for answering :) Good luck!

**Comment by harrislapiroff** [comment]
I'll second a request for webhook support! I'm currently trying to write automated tests for my Stripe webhook view and would love a way to do it without requiring active credentials my stripe sandbox to be stored on CI. (If anyone has recommendations for ways to do that before this feature lands, I'd love to hear them!)

**Comment by j4rs** [comment]
@harrislapiroff did you take a look to https://github.com/stripe-ruby-mock/stripe-ruby-mock - it supports simulating webhooks calls out of the box.

**Comment by harrislapiroff** [comment]
@j4rs I didn't! Thanks for the tip. Will check it out.

**Comment by anniel-stripe** [comment]
Hello, apologies for the very delayed update here! I'm closing this issue as out of scope, since the scope of stripe-mock has been narrowed significantly since its inception in 2017. You can refer to [our README](https://github.com/stripe/stripe-mock#future-plans) for more details, but TL;DR we don't plan to add more sophisticated testing features to stripe-mock.
