### ISSUE TITLE
Creating plan doesn't return a product object

### ISSUE THREAD

**Issue by dpash** [stripe/stripe-mock#175]
Running the following Java against the mock results in a NPE as the response doesn't include the Product object in the json.

```java
Plan stripePlan = Plan.create(planParams);

log.info("Plan created successfully. planId: {} Plan name: {} ", stripePlan.getId(), stripePlan.getProductObject().getName());

```
JSON:

```json
{
    "active":true,
    "aggregate_usage":null,
    "amount":2000,
    "billing_scheme":"per_unit",
    "created":1234567890,
    "currency":"gbp",
    "id":"900",
    "interval":"month",
    "interval_count":1,
    "livemode":false,
    "metadata":{

    },
    "nickname":null,
    "object":"plan",
    "product":"sampleplan",
    "tiers":null,
    "tiers_mode":null,
    "transform_usage":null,
    "trial_period_days":null,
    "usage_type":"licensed"
}
```

**Comment by ob-stripe** [comment]
@dpash [`product`](https://stripe.com/docs/api/plans/object#plan_object-product) is an expandable field, by default it only contains a string with the ID of the resource. If you want the full object, you need to request it using the `expand` parameter in your request: https://stripe.com/docs/api/expanding_objects.

**Comment by dpash** [comment]
Sorry, yes, adding that to the expand parameter resolved the issue. 

Sorry again for the noise.

**Comment by ob-stripe** [comment]
No worries at all!
