### ISSUE TITLE
SetupIntent missing client_secret

### ISSUE THREAD

**Issue by tristanoneil** [stripe/stripe-mock#181]
I wasn't entirely sure if this issue belongs here or the OpenAPI repo but the response for a SetupIntent returns `null` for the `client_secret`.

This being `null` causes issues when trying to test at the user level when used in conjunction with react-stripe-elements because of https://github.com/stripe/react-stripe-elements/blob/3fb4e57ec439f652857cbfd21597f00a2c7af5a7/src/co...

**Comment by pakrym-stripe** [comment]
Hi, sorry for the extremely delayed response. [`setup_intent`](https://github.com/stripe/stripe-mock/blob/master/openapi/fixtures3.json#L2938-L2941) now has a client secret.
