### ISSUE TITLE
Allow API Key to use restricted key

### ISSUE THREAD

**Issue by marty331** [stripe/stripe-mock#199]
Currently stripe-mock returns an error when using a restricted key (rk_) vs using the standard secret key (sk_).  A very simple change would resolve this and allow for a developer to use either.  It is much more common (on my project anyway) for developers to be issued restricted keys so this would greatly improve the dev workflow.

Below is the code change needed (I tried to submit a PR but was unable):
server.go file - line 781-83
Current structure:
`if keyParts[0] != "sk" {
		return false
	}`
Updated fix:
`if keyParts[0] != "sk" || keyParts[0] != "rk" {
		return false
	}`

**Comment by brandur-stripe** [comment]
Yep, seems reasonable — opened #200 to fix.

**Comment by marty331** [comment]
Thank you.

**Comment by brandur-stripe** [comment]
Released as v0.75.0.
