### ISSUE TITLE
Refactor to make stripe-mock useable as a package

### ISSUE THREAD

**Issue by shoenseiwaso** [stripe/stripe-mock#206]
It would be great to be able to embed `stripe-mock` as a package in Go. For example, something like:
```go
package abc

import (
   "testing"
   "stripe/stripe-mock"
)

func TestMyApp(t *testing.T) {
   mock := stripe.RunMock()
   defer mock.Stop()

   // perform tests against stripe-mock here
}
```

In order to make this work, probably two changes are required:
- Move the bulk of the functionality out of `package main`. This could be accomplished either by moving most of the functionality in `github.com/stripe/stripe-mock` to another package in a sub-folder, or moving `package main` into a sub-folder (e.g., `github.com/stripe/stripe-mock/stripe-mock`). The former is probably preferred because no change would be required to anyone who has `go get -u github.com/stripe/stripe-mock` in their tooling.
- Go modularize `stripe-mock` (i.e., `go mod init` => `go.mod`, `go.sum`).

**Comment by richardm-stripe** [comment]
This was shipped in #265
