### ISSUE TITLE
Mock Oauth Token endpoint for connect?

### ISSUE THREAD

**Issue by shanestillwell** [stripe/stripe-mock#209]
Is it possible to mock the connect oauth token endpoint found at
https://stripe.com/docs/connect/oauth-reference#post-token-request

I've tried this without success
```
curl  http://localhost:12111/oauth/token -H "Authorization: Bearer sk_test_123" -d code=ac_GZz2Zad6864TDtPalY7u1QgZUOwejfq4 -d grant_type=authorization_code
```

I get the error
```
{
  "error": {
    "message": "Unrecognized request URL (POST: /oauth/token).",
    "type": "invalid_request_error"
  }
}
```

**Comment by remi-stripe** [comment]
@shanestillwell At the moment, stripe-mock doesn't support the OAuth endpoint as those are not part of our core API (on api.stripe.com) and instead are on connect.stripe.com.

**Comment by shanestillwell** [comment]
@remi-stripe 

Thanks for clarifying.
