### ISSUE TITLE
Customer object missing attributes

### ISSUE THREAD

**Issue by vready333** [stripe/stripe-mock#212]
Customer name, address not allowed: additional properties are not allowed: name, address","type":"invalid_request_error"

**Comment by remi-stripe** [comment]
@vready333 The latest version of stripe-mock does support those properties. I have installed 0.80.0 locally and this command just works:

```
 curl http://localhost:12111/v1/customers   -u sk_test_123:   -d name=aaaa
```

The fixture used internally also returns `address: null` and `name: null`. We won't reflect back the parameters that you're passing as stripe-mock only returns the internal fixture.

Are you sure you have the latest version installed and running?

**Comment by vready333** [comment]
Yes, this was tried using code after get on 2/12/2020. I could try again. My -version returns master (stripe-mock master)

**Comment by vready333** [comment]
I just did a get again today. Seems to be working now. No error and does send back a null. Thanks.
