### ISSUE TITLE
Updating Subscription Item returning empty list for tax_rates

### ISSUE THREAD

**Issue by leo-bao-prodigy** [stripe/stripe-mock#213]
Hi,

When testing Stripe with python using stripe-mock, calling the [modify](https://stripe.com/docs/api/subscription_items/update?lang=python) function returned an empty list for `tax_rates` despite a tax rate being set in the function call. For example, calling the function with:
```
response = stripe.SubscriptionItem.modify(
    "si_someid",
    tax_rates=["txr_123"]
)
```
Ends up returning a Subscription Item object with an empty list in the `tax_rates` field.

Similar thing happens with `create` where an empty list for tax is returned despite setting a tax rate in the function call. Issue started on version 0.80.0, perhaps related to issue [210](https://github.com/stripe/stripe-mock/issues/210) in some way?

Thanks

**Comment by remi-stripe** [comment]
@leo-bao-prodigy stripe-mock does not reflect the parameters back today unfortunately. What it does is validate that the format of the request is correct (supported parameters and endpoints) and then it responds with a fixed version of a Subscription Item object taken from the internal fixture. The only thing we reflect back are ids like the `si_someid` you are passing.

**Comment by leo-bao-prodigy** [comment]
Ah, so I'm assuming the basic fields like id are reflected as you said but more complex ones like `tax_rates` are fixed values? 
Thanks for the quick reply!

**Comment by leo-bao-prodigy** [comment]
My bad, closed the issue a bit early, a couple more questions on this
Up until recently, `default_tax` was reflected and included in the return value but starting version 0.80.0, this was removed following the fix for the issue linked above, I'm wondering if this was intended functionality or not?
Thanks

**Comment by brandur-stripe** [comment]
Hey @leo-bao-prodigy, sorry about the breakage here.

I think you have it roughly right already — stripe-mock will try to reflect values back in responses, but it gives up on doing so unless a parameter's type in the request matches the field's type in the response according to the OpenAPI schema.

This is different from how it was before #211, where we'd be much more optimistic about what we could replace in the response. The reason for the change was fields like tax rates, which come into a request as a string, but then transform into an object in the response — stripe-mock would previously set those as a string in the response as well, which was wrong.

Ideally, we'd be able to generate a much more sensible answer despite the mismatch, but coming up with broad heuristics that we can apply everywhere without the benefit of the API's internal logic is fairly difficult.

**Comment by leo-bao-prodigy** [comment]
Ah, I see
I'm assuming theres no plans in the near future to generate more "complete" return values then?

**Comment by brandur-stripe** [comment]
Yes, sorry :/ I'd personally love to do this, but it basically boils down to a question of priorities/resources.

**Comment by leo-bao-prodigy** [comment]
No worries, thanks for taking the time to answer my questions!
