### ISSUE TITLE
Null Metadata value causes error

### ISSUE THREAD

**Issue by vready333** [stripe/stripe-mock#217]
Passing a null value for metadata results in error but ok in live mode.
Since shipping attribute is optional also, tried that as well to make sure it works.
stripe-mock 0.82.0
Routing to 212 path(s) and 353 endpoint(s) with 353 validator(s)
Listening for HTTP at address: [::]:12111
Listening for HTTPS at address: [::]:12112
Request: POST /v1/customers

Please note "metadata:".

name:Optimus Prime
email:optimus@cybertron.net
address[line1]:123 Hello St
address[line2]:
address[city]:El Segundo
address[state]:CA
address[country]: USA
address[postal_code]:  
  
Pass 200 OK 9ms 3.33 KB 

name:Optimus Prime
email:optimus@cybertron.net
address[line1]:123 Hello St
address[line2]:
address[city]:El Segundo
address[state]:CA
address[country]: USA
address[postal_code]:
metadata[test]:

Pass 200 OK 9ms 3.33 KB 

name:Optimus Prime
email:optimus@cybertron.net
address[line1]:123 Hello St
address[line2]:
address[city]:El Segundo
address[state]:CA
address[country]: USA
address[postal_code]:
metadata:                        <<<<
shipping[name]:Shipper Shipping
shipping[address][line1]:123 Main Street
shipping[address][city]:San Francisco
shipping[address][state]:CA
shipping[address][postal_code]:94111
shipping[address][country]:US

Mock: Fail {"error":{"message":"Request validation error: validator 0xc00099c1e0 failed: object property 'metadata' validation failed: cannot get property names from this value (Kind: string)","type":"invalid_request_error"}}

Live: Pass

name:Optimus Prime
email:optimus@cybertron.net
address[line1]:123 Hello St
address[line2]:
address[city]:El Segundo
address[state]:CA
address[country]: USA
address[postal_code]:
metadata[test]:Test             
shipping:                       

Pass 200 OK 12ms 3.33 KB

name:Optimus Prime
email:optimus@cybertron.net
address[line1]:123 Hello St
address[line2]:
address[city]:El Segundo
address[state]:CA
address[country]: USA
address[postal_code]:
metadata[test]:Test                <<<<
shipping[name]:Shipper Shipping
shipping[address][line1]:123 Main Street
shipping[address][city]:San Francisco
shipping[address][state]:CA
shipping[address][postal_code]:94111
shipping[address][country]:US

Pass 200 OK 22ms 3.33 KB

[mockbugs.txt](https://github.com/stripe/stripe-mock/files/4293966/mockbugs.txt)

**Comment by remi-stripe** [comment]
@vready333 Thanks a lot for the report! We usually discourage passing empty matadata hash on creation. Our openapi spec blocks this for Customer creation explicitly which is why stripe-mock blocks this at the moment. Our API is a bit more lenient on some endpoints to decrease the number of errors developers experience. But if you're using stripe-mock and hitting this error, the best approach would be to skip sending metadata as a parameter if it's not set at all.

**Comment by vready333** [comment]
Thanks. I had pointed out the same to the developer as a fix as this is how I got around it. Your response helps better.

**Comment by ob-stripe** [comment]
@vready333 The latest version of stripe-mock (0.84.0) should now reflect the behavior of the API.
