### ISSUE TITLE
Unsupported property: pay_immediately

### ISSUE THREAD

**Issue by DaleSeo** [stripe/stripe-mock#220]
The `pay_immediately` property is not being accepted when creating subscriptions as follows.

```sh
$ curl http://localhost:12111/v1/subscriptions \
  -u sk_test_123: \
  -d customer=cus_123 \
  -d "items[0][plan]"=plan_123 \
  -d pay_immediately=true
{
  "error": {
    "message": "Request validation error: validator 0xc0006b8180 failed: additional properties are not allowed: pay_immediately",
    "type": "invalid_request_error"
  }
}
```

I'd like to ask to add support for this parameter because it's required in order to have Avalara to calculate tax. Stripe support enables the `pay_immediately` option on account basis for Avalara integration. For more information, please refer to the following Avalara docs.

- https://help.avalara.com/Frequently_Asked_Questions/Stripe_Invoicing_FAQ/How_do_I_charge_tax_on_subscription_invoice_in_Stripe%3F
- https://help.avalara.com/Frequently_Asked_Questions/Stripe_Invoicing_FAQ/Why_are_my_subscription_invoices_in_Stripe_not_calculating_tax_or_posting_to_AvaTax%3F

**Comment by remi-stripe** [comment]
@DaleSeo This feature is not public in the API today. It's only allowed for users relying on the Avalara integration. For that reason, it is not supported on stripe-mock, but it would work on your Stripe account if you have the feature enabled. If not, you would have to ask our support team to enable this for you: https://support.stripe.com/contact
