### ISSUE TITLE
Bad status when update PaymentIntent

### ISSUE THREAD

**Issue by jeans11** [stripe/stripe-mock#225]
Hi!

When a payment intent is updated with `payment_method` the status of the payment intent is still on `requires_payment_method`.

```java
PaymentIntent paymentIntent = PaymentIntent.retrieve("...");
Map<String, String> params = new HashMap();
params.put("payment_method", "...");
PaymentIntent paymentIntent = paymentIntent.update(params)
paymentIntent.getStatus();
// "requires_payment_method"
```

**Comment by remi-stripe** [comment]
@jeans11 stripe-mock is not "stateful" and it won't return the exact state that the API would return in production. It's here to mock the API and return valid-looking JSON but it doesn't have much "business logic".

**Comment by jeans11** [comment]
Thanks @remi-stripe.
