### ISSUE TITLE
BalanceTransaction doesn't return application fee

### ISSUE THREAD

**Issue by mikker** [stripe/stripe-mock#24]
As the title says I'm getting no `application_fee` in my returned balance transaction when using

```ruby
        stripe_charge = Stripe::Charge.create({
          source: token.id,
          amount: stripe_amount,
          currency: from.currency,
          application_fee: application_fee,
          expand: ['balance_transaction']
        }.reverse_merge(opts), stripe_account: stripe_account)
```

**Comment by mikker** [comment]
I might've misunderstood the purpose of this project. It isn't supposed to be used as a "mock backend" for my app is it?

**Comment by brandur-stripe** [comment]
Thanks for logging @mikker!

As a quick note: stripe-mock is currently quite stupid when it comes to actual Stripe domain logic. It would seem intuitive that if you passed an `application_fee` on the way in, then you'd get that same `application_fee` on the response, but in fact what's happening is that it always just uses a pre-defined fixture for _every_ response and adds any extra required fields if necessary.

> I might've misunderstood the purpose of this project. It isn't supposed to be used as a "mock backend" for my app is it?

I think plausibly we could go this direction at some point, but right now stripe-mock is totally stateless and knows very little about how Stripe would actually behave. It's useful for request validation and to get a basic response back that's formatted in a valid way, but it's missing everything in between.

**Comment by mikker** [comment]
I see. Makes sense – copying all the logic behind the requests as well as the interface would undeniably increase the scope _a bit_.

I'll keep my test suite as is for now 😄 Thanks!
