### ISSUE TITLE
Add support for `requested_capabilities` on create account endpoint POST /v1/accounts

### ISSUE THREAD

**Issue by filias** [stripe/stripe-mock#243]
I have been using stripe-mock ('Stripe-Mock-Version': '0.99.0') for testing a python application and when I create an account (POST /v1/accounts), of type express, with the `requested_capabilities` parameter I have this error:

`self = <stripe.api_requestor.APIRequestor object at 0x7ffd4005eb80>
rbody = '{"error":{"message":"Request validation error: validator 0xc0006f72c0 failed: additional properties are not allowed: requested_capabilities","type":"invalid_request_error"}}', rcode = 400
resp = OrderedDict([('error', OrderedDict([('message', 'Request validation error: validator 0xc0006f72c0 failed: additional properties are not allowed: requested_capabilities'), ('type', 'invalid_request_error')]))])
rheaders = {'Idempotency-Key': 'b7b40a4d-4034-44d4-bda9-0e82188be7fd', 'Request-Id': 'req_123', 'Stripe-Mock-Version': '0.99.0', 'Date': 'Tue, 13 Oct 2020 12:40:46 GMT', 'Content-Length': '173', 'Content-Type': 'text/plain; charset=utf-8'}
...

E       stripe.error.InvalidRequestError: Request req_123: Request validation error: validator 0xc0006f72c0 failed: additional properties are not allowed: requested_capabilities`

When I do the same request in test_mode it succeeds.
Is it so that `requested_capabilities` is not a supported parameter?

**Comment by remi-stripe** [comment]
@filias `requested_capabilities` is deprecated and discouraged. It was replaced by `capabilities` instead which is the new canonical way to control capabilities on Account: https://stripe.com/docs/api/accounts/create#create_account-capabilities

We recommend that you stop using `requested_capabilities` even though it still works it's undocumented and will be removed in the future.

**Comment by filias** [comment]
@remi-stripe Thank you for your clarification. Definitely this part of the docs was very misleading https://stripe.com/docs/connect/express-accounts regarding `requested_capabilities`. Maybe something to improve.

Thanks again 👍

**Comment by remi-stripe** [comment]
Nice catch for that doc, I'll work on a fix today!
