### ISSUE TITLE
Configure webhooks in stripe-mock

### ISSUE THREAD

**Issue by devansh-dalal** [stripe/stripe-mock#248]
Is there a way to configure webhooks in stripe-mock local docker container environment?

**Comment by remi-stripe** [comment]
@devansh-dalal Can you clarify what you mean by this exactly? What are you trying to do with stripe-mock that would need a webhook endpoint?

**Comment by devansh-dalal** [comment]
So, we have some webhook endpoints configured in stripe dashboard, 
In our test automations, we are using stripe-mock to test various workflows relating stripe APIs, 
To test those endpoints of our backend with a local stripe docker which can trigger events just like stripe APIs is a great fit for our testing.

So, was wondering if its possible to configure webhooks in stripe-mock similar to stripe?

**Comment by remi-stripe** [comment]
stripe-mock just mocks the API we have today. It can't mock your webhook endpoint since that would be your own code that reacts to our events. What you could do here is use the Stripe CLI for example to expose your local instance: https://stripe.com/docs/stripe-cli

Do you think that could help?

**Comment by devansh-dalal** [comment]
Yes, makes sense. stripe-cli can help. Thanks @remi-stripe

**Comment by cedvdb** [comment]
@remi-stripe So `stripe trigger ...` can make `stripe-mock` fire events ?

**Comment by remi-stripe** [comment]
@cedvdb no, the CLI and stripe-mock are completely separate tools and don't work together. But yes the CLI can be used to trigger Events. I recommend reading our docs 
* https://docs.stripe.com/stripe-cli
* https://docs.stripe.com/stripe-cli/triggers

If you have follow up questions, please work with our support team for help instead: https://support.stripe.com/contact

**Comment by cedvdb** [comment]
We use the cli to trigger events. But this comment chain makes it ambiguous if the events can be triggered on stripe mock somehow. For future googlers and myself, this could be cleared up. Which I will do here:

The cli cannot be used to trigger events in stripe mock server
