### ISSUE TITLE
Question: use case

### ISSUE THREAD

**Issue by hiveship** [stripe/stripe-mock#262]
Hello,

Not really an issue with the project but more a question about my use case.

We are integrating with Stripe using the Stripe Connect (we create an account and create payment intents + listen webhooks).

We need to perform end to end testing for load testing.
I am wondering how I can replace the Stripe for this kind of tests?
I would prefer to avoid calling the real Stripe API in a test mode, especially when doing load testing.

My main question is how I can emulate the Stripe behavior on the frontend part?

- To create an account, we call the "createAccountLink" endpoint and Stripe returns an URL with a UI to complete. Using the mock server I get https://richardm-manage-mydev.dev.stripe.me/setup/s/RHifTZTLkNS8 which is not reachable on my computer. Am I missing something?
- To create and validate paymentIntent, we onboard the Stripe US (to enter payment method etc)

Do you have any recommandation for me please? More than happy to provide more details if needed.

**Comment by remi-stripe** [comment]
@hiveship stripe-mock only returns "fake data that looks mostly correct". So all URLs are random/ad-hoc and can't be loaded. We don't have a way to mock the API and get real URLs that you could load.
While it's a bit of a non-answer, you should skip load testing our Connect Onboarding flow since this runs fully on our server. We also don't have  away to unit test hosted flows like this one today beyond doing it by hand. You should instead use accounts that have been already created with test information provided already so that all functionalities are enabled already.

**Comment by hiveship** [comment]
@remi-stripe  Understood, thanks. My need is not to load test the Stripe part, as you said it's running on your server and we fully trust you on this topic.

Our system is processing a lot of payments and we need to load test our system when there is a lot of payment. That's why I want to be able to create a payment intent and then to get a webhook notification with the wanted state (succeedd, failed, canceled, requires action...). Do you have a solution for that?

**Comment by remi-stripe** [comment]
You would use stripe-mock to mock the API request and then you'd save the payload of an event for example a `payment_intent.succeeded` event and send that event to your webhook handler on your end. We don't really have a way to load test this on your end automatically today unfortunately so you'd have to build this from scratch in your own test suite.

**Comment by hiveship** [comment]
Very clear, thanks for your answers!
I think we can close this issue for now and I will open a new one if I needed further information when implementing it.

**Comment by hiveship** [comment]
@remi-stripe I don't find documentation about this, but can you tell me if the stripe-mock backend also support webhooks?
My application is massively using the Stripe webhooks notifications.

**Comment by remi-stripe** [comment]
@hiveship It does not support webhook today unfortunately. You'll have to build this logic yourself or you can use the Stripe CLI for this https://stripe.com/docs/cli

Please talk to our support team directly for help with your integration as Github issues are limited to bugs with the library itself. You can contact them on https://support.stripe.com/contact/email or directly in Discord: https://stripe.com/go/developer-chat
