### ISSUE TITLE
lestrrat-go is changing "master" branches to "main"

### ISSUE THREAD

**Issue by omnilord** [stripe/stripe-mock#282]
I have a funny suspicion that this is upstream in one of the lestrrat-go packages (since I cannot find "option" in stripe-mock), but @lestrrat-go has changed "master" to "main" on several of their packages and it breaks setting up stripe-mock.

Is there anything we can do when running `go get -u github.com/stripe/stripe-mock` that will make sure to checkout main instead of master for these repositories?

```
$ go get -u github.com/stripe/stripe-mock
# cd $GOPATH/src/github.com/lestrrat-go/option; git checkout master
error: pathspec 'master' did not match any file(s) known to git.
package github.com/stripe/stripe-mock
	imports github.com/lestrrat-go/jsschema
	imports github.com/lestrrat-go/jsref
	imports github.com/lestrrat-go/jspointer
	imports github.com/lestrrat-go/structinfo
	imports github.com/lestrrat-go/option: exit status 1
# cd $GOPATH//src/github.com/lestrrat-go/pdebug; git checkout master
error: pathspec 'master' did not match any file(s) known to git.
package github.com/stripe/stripe-mock
	imports github.com/lestrrat-go/jsschema
	imports github.com/lestrrat-go/jsref
	imports github.com/lestrrat-go/jspointer
	imports github.com/lestrrat-go/structinfo
	imports github.com/lestrrat-go/pdebug: exit status 1
```

**Comment by richardm-stripe** [comment]
Hello @omnilord, what `go version` are you using? I'm seeing slightly different behavior on my environment.

**Comment by omnilord** [comment]
@richardm-stripe
```
ubuntu@TEST:~$ go version
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64
```

**Comment by richardm-stripe** [comment]
Closing this due to staleness. 

Sorry for losing track here @omnilord. I hope this is an ecosystem problem that has resolved, but if you are still having difficulty, feel free to re-open. Alas `go version xgcc` isn't enough information to figure out the corresponding go version, I think means it is built from source.
