### ISSUE TITLE
Support subscription discount removal

### ISSUE THREAD

**Issue by kxhitiz** [stripe/stripe-mock#289]
Looks like currently it does not support the endpoint for deleting discount from subscription
[https://stripe.com/docs/api/discounts/subscription_delete](https://stripe.com/docs/api/discounts/subscription_delete)

   ```
Failure/Error: Stripe::Subscription.delete_discount(stripe_subscription_id)
  Stripe::InvalidRequestError:
       No such subscription: test_su_4/discount
     # /Users/kshitizgurung/.rvm/gems/ruby-2.7.5/gems/stripe-ruby-mock-2.5.8/lib/stripe_mock/instance.rb:168:in `assert_existence'
```

Instead, the request is matched to cancel the subscription. Hence stripe-mock tries to cancel subscription instead of deleting discount. 
Would be a nice addition to support this endpoint.

**Comment by richardm-stripe** [comment]
Hello @kxhitiz! Sorry for the slow response.

I think you meant to open this issue on https://github.com/stripe-ruby-mock/stripe-ruby-mock (judging from your stack trace). I don't think you use this project, `stripe-mock` which isn't stateful like stripe-ruby-mock, and is intended only for very basic sanity checks about the shapes of requests and responses.
