### ISSUE TITLE
DockerImage : lastest is too old

### ISSUE THREAD

**Issue by bobbyangers** [stripe/stripe-mock#294]
Your version of stripe-mock (0.110.0) is too old. The minimum version to run this test suite is 0.119.0. Please see its repository for upgrade

**Comment by alko89** [comment]
Use `stripe/stripe-mock`

**Comment by okapies** [comment]
Googling *"stripe-mock docker"* leads me to `stripemock/stripe-mock` instead of `stripe/stripe-mock`. I think you should takedown the old repository from Docker Hub.

**Comment by MaxBlaushild** [comment]
I also just ran into this. ChatGPT will recommend `stripemock/stripe-mock` as well since it's training data is old
