### ISSUE TITLE
Metadata doesn't work?

### ISSUE THREAD

**Issue by travisjeffery** [stripe/stripe-mock#30]
Seems creating resources with metadata doesn't (or at least every one I've tried).

See these logs for instance:

```
Request: POST /v1/subscription_items
Response schema: {
  "$ref": "#/components/schemas/subscription_item"
}
Request data: metadata%5BclusterId%5D=xx2&metadata%5BaccountId%5D=test-account&plan=ruby-express-932&subscription=sub_XXX
Expansions: []
Response data: {
  "created": 1505872622,
  "id": "si_YYY",
  "metadata": {},
  "object": "subscription_item",
  "plan": {
    "amount": 999,
    "created": 1505549157,
    "currency": "usd",
    "id": "ruby-express-932",
    "interval": "month",
    "interval_count": 1,
    "livemode": false,
    "metadata": {},
    "name": "Ruby Express",
    "object": "plan",
    "statement_descriptor": null
  },
  "quantity": 1
}
Response: elapsed=142.324µs status=200
```

**Comment by brandur-stripe** [comment]
Hey Travis, thanks for trying things out!

I don't think the README is clear enough on this, but currently the responses that you get from stripe-mock don't have much to do with the requests that you sent in: it does request validation, and as long as a request looks okay, it responds with a bundled fixture for the appropriate resource.

We're thinking of producing a "stateful" model where stripe-mock would try to be smarter about what it returns as field values and even keep state across requests, but we're not there yet. See #19 for some additional detail.

**Comment by travisjeffery** [comment]
Ah, ok. Yeah I assumed it doing some kind of persistence already. Thanks for quick response.
