### ISSUE TITLE
A newly created checkout session status is coming as "expired"

### ISSUE THREAD

**Issue by shadab14meb346** [stripe/stripe-mock#303]
When I am creating a checkout session it's returning a checkout.session object but the status is "expired" ideally it should be "open

https://user-images.githubusercontent.com/31199288/168536288-6b92bf93-7b63-4e93-99fa-c11a3ca4b02b.mp4

"

**Comment by Kryniol** [comment]
Same here, also the checkout URL is empty. Would it be possible to always return an active checkout session from the mocked API?

**Comment by anniel-stripe** [comment]
Hello, apologies for the delay in reponse here! This is now fixed in v0.150.0. The checkout session fixture now has `status` set to `open`.
