### ISSUE TITLE
Return mock of complex objects

### ISSUE THREAD

**Issue by alko89** [stripe/stripe-mock#305]
I've been using stripe-mock in my tests and its working great for getting basic mocked data, however it fails short when I want to test my code with more complex ones.

For example, retrieving a metered price or a subscription item with price tiers will return an empty array. Is it possible to modify this behavior? A good option would be to be able to create these prices on the mock server so they would return expected values when querying that specific ID, though it might defeat the purpose of a mock server :smile: 

```
{
      active: true,
      billing_scheme: 'per_unit',
      created: 1234567890,
      currency: 'usd',
      id: 'price_1GwXq7QZxX7QxX',
      livemode: false,
      lookup_key: null,
      metadata: {},
      nickname: null,
      object: 'price',
      product: 'prod_LdLtsGBxTz8RWH',
      recurring: {
        aggregate_usage: null,
        interval: 'month',
        interval_count: 1,
        usage_type: 'licensed'
      },
      tax_behavior: 'unspecified',
      tiers: [],
      tiers_mode: null,
      transform_quantity: null,
      type: 'recurring',
      unit_amount: 2000,
      unit_amount_decimal: '2000'
}
```

**Comment by anniel-stripe** [comment]
Hi, sorry for the delayed update here! I'm closing this issue as out of scope, as we don't have plans to expand the scope of stripe-mock to be more than a basic validation tool. You can refer to [our README](https://github.com/stripe/stripe-mock#future-plans) for more details.
