### ISSUE TITLE
The response from `/v1/invoices/:id/finalize` is wrong

### ISSUE THREAD

**Issue by okapies** [stripe/stripe-mock#315]
The [document](https://stripe.com/docs/api/invoices/finalize) for `/v1/invoices/:id/finalize` API says *"Returns an invoice object with `status=open`"* but stripe-mock always return it with `status=draft`.

```bash
$ curl \
  -XPOST \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -H "Authorization: Bearer sk_test_123" \
  http://localhost:12111/v1/invoices/in_test_123/finalize
{
  ...
  "status": "draft",
  ...
}
```

**Comment by remi-stripe** [comment]
@okapies stripe-mock doesn't really have logic to mimic the API behaviour so this is an expected limitation. It's here to help you mock our API and getting a JSON response for the right resource.

Returning the right `status` might not seem too hard, but there's a lot more complexity than this in our API that we'd need to encode inside stripe-mock and keep up to date with changes (which would also be surprising). For example, on invoice finalization, we need a PaymentIntent id in `payment_intent`, but only if the amount is higher than the minimum amount in that currency, we also need to set `status_transition[finalized_at]` and possibly other changes.

I hope this clarifies the situation!
