### ISSUE TITLE
Add an ability to register user-defined responses with idempotency_key

### ISSUE THREAD

**Issue by okapies** [stripe/stripe-mock#316]
According to [this post](https://github.com/stripe/stripe-mock/issues/315#issuecomment-1139700416), stripe-mock is not able to return responses meeting the specifications. One idea is that stripe-mock could provide an additional API that can register user-defined responses with [`Idempotency-Key`](https://stripe.com/docs/api/idempotent_requests) in advance, and returns it later for testing. What do you think?

**Comment by anniel-stripe** [comment]
Hi, sorry for the late update here! I'm closing this issue as out of scope, as we don't have plans to add more features to stripe-mock, and intend for it to remain a basic validation tool. You can refer to [our README](https://github.com/stripe/stripe-mock#future-plans) for more details.
