### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dmgawel** [stripe/stripe-mock#33]
Hi,

I consider borrowing stripe-mock hack for yaml parsing (`mapstr.go`) for open source project but unfortunately stripe-mock does not have any license. I want to make sure it's OK and follows your intentions. Could you please consider adding a license?

**Comment by brandur-stripe** [comment]
Hi @dmgawel,

Apologies for the delay here — I've been on vacation for a few weeks, and might be the only person following the issues on this repository closely.

We license our other open source projects under MIT and I've copied that convention to this repository as well. `LICENSE` file incoming in #37.
