### ISSUE TITLE
Linux install not working based on README

### ISSUE THREAD

**Issue by snewcomer** [stripe/stripe-mock#34]
I followed the directions with installing go then running `go get -u github.com/stripe/stripe-mock`.  However, after closing my terminal and trying to restart my computer as well, `stripe-mock` wasn't a thing?

Any helpful debugging techniques anybody can think of?

**Comment by snewcomer** [comment]
Had to add the following
```
export GOPATH=$HOME/go                                                                                             
export PATH=$PATH:$GOPATH/bin 
```

**Comment by snewcomer** [comment]
If ya'll think it is good to add this to the directions, I can add it to the README!

**Comment by brandur-stripe** [comment]
Glad to see that you got it working!

The instructions kind of assume a relatively functional Go installation. I don't think we should add too much more detail there, but some kind of link elsewhere (to Go setup docs for example) might be in order.

Also, for what it's worth, if you're using Go 1.8+ `GOPATH` now has a default of `$HOME/go` so you don't have to set that explicitly anymore.
