### ISSUE TITLE
Can we specify what data is on a checkout session retrieval?

### ISSUE THREAD

**Issue by shaun-wild** [stripe/stripe-mock#342]
I'm sure there are many other scenarios like this.

If I call `Session.retrieve(sessionID)`, `subscription` is null (If using the stripe-mock endpoint), which means I cannot test that the correct values are being returned from my endpoint. 

Is it possible to configure whether a subscription will be returned or not etc?

**Comment by remi-stripe** [comment]
Unfortunately this is not something we support today and stripe-mock just gives one example response based on a hardcoded fixture so you can't override any of the properties in the response. Our recommendation would be to do your own mock in that case with your own local fixture instead.

**Comment by shaun-wild** [comment]
Okay, thanks for the clarification!
