### ISSUE TITLE
Payment link creation not currently mocked ?

### ISSUE THREAD

**Issue by nbensalha** [stripe/stripe-mock#346]
Hi,

While trying to use the Stripe PHP SDK and make calls to a Docker Stripe Mock server hosted locally, I get the following error:

`Stripe\Exception\InvalidRequestException: Unrecognized request URL (POST: /v1/payment_links)`

Questions: is there something I am doing wrong or is it just that this endpoint hasn't been implemented yet ? If so, are there any plans to roll it out ?

Thanks

**Comment by remi-stripe** [comment]
@nbensalha You likely have an old version of stripe-mock on your end from before the PaymentLinks API was built/shipped. I'd recommend making sure you upgrade to the latest version of stripe-mock 0.140.0

**Comment by nbensalha** [comment]
> @nbensalha You likely have an old version of stripe-mock on your end from before the PaymentLinks API was built/shipped. I'd recommend making sure you upgrade to the latest version of stripe-mock 0.140.0

thanks @remi-stripe , we were indeed still using the older version, we updated to the newest one and it works fine now :+1:
