### ISSUE TITLE
Endpoint for file uploads?

### ISSUE THREAD

**Issue by joshsmith** [stripe/stripe-mock#35]
Is there supposed to be an endpoint for file uploads?

Thanks!

**Comment by brandur-stripe** [comment]
It should, but no it's not quite in here yet. We're moving to a set of new file endpoints pretty soon in the main API, and I _think_ they'll show up in the OpenAPI spec once that happens, after which stripe-mock will be able to support them.

**Comment by snewcomer** [comment]
@brandur-stripe 👋 Was curious on the ability to support file uploads.  Anything I can help with?

**Comment by brandur-stripe** [comment]
@snewcomer Good question, and thanks for the offer! Actually, I've been lookin at this stuff lately, and I think we could get a patch in now. Let me take a quick look.

**Comment by brandur-stripe** [comment]
This had a few more gotchas than I'd expected, but I'm pretty close to a working version.

**Comment by brandur-stripe** [comment]
Okay, I just shipped v0.14.0!

The file tests in `stripe-ruby` are currently special-cased so that they don't hit `stripe-mock`, but I just unspecial-cased them, and they seem to work.

Try it and let me know if you see any problems. Closing this out for now.

**Comment by brandur-stripe** [comment]
And actually, I found a bug that's causing request parameters for those endpoints not be validated ... a fix can be tracked against #69, which is related.

**Comment by brandur-stripe** [comment]
@snewcomer Would you mind trying to upgrade to 0.15.0? the previous version did respond at the file endpoints, but it wasn't validating incoming parameters correctly. 0.15.0 should be an adequate fix for that problem, and I've had some success testing `stripe-ruby` against it. (Thanks!)

**Comment by brandur-stripe** [comment]
@snewcomer Yeah, it should at `POST /v1/files` (I've verified in other languages that this seemsto work — see https://github.com/stripe/stripe-ruby/pull/644 for example). One caveat is that this endpoint is quite unusual in that it expects to have request bodies encoded as `multipart/form-data` to support a file upload.
