### ISSUE TITLE
Cardholder replacment because of `cardholder_reassigned` reason

### ISSUE THREAD

**Issue by 1nir1** [stripe/stripe-mock#354]
Hi,
We are trying to test cardholder replacement using stripe-mock.
We send a card id as replacement-for value, and `cardholder_reassigned` as replacment_reason value, and we receive the following error:
`Request validation error: validator 0xc00172a810 failed: object property 'type' validation failed: value is not in enumeration
Response: elapsed=2.034333ms status=400`
But when checking this flow in our actual testing environment, all works as expected.
Can you please assist?

Thanks in advance

**Comment by remi-stripe** [comment]
@1nir1 stripe-mock only supports officially released APIs and related parameters/properties. The feature you are using is currently in private beta and only available to a few accounts so it is not in stripe-mock. You'll need to work around stripe-mock in that case and mock your own code yourself.

**Comment by 1nir1** [comment]
@remi-stripe, thank you for the quick response
