### ISSUE TITLE
'Create a card' responds with 'bank account' object instead of 'card object'

### ISSUE THREAD

**Issue by ruzaikr** [stripe/stripe-mock#36]
When I try to create a credit card using the following request:

`curl http://localhost:12111/v1/customers/cus_BsLON0VirK4qBO/sources \
   -u sk_test_123: \
   -d source=tok_1B3xSU2eZvKYlo2Cj8aaqtGj`

I get this:

`{
  "account": "acct_1032D82eZvKYlo2C",
  "account_holder_name": "Jane Austen",
  "account_holder_type": "individual",
  "bank_name": "STRIPE TEST BANK",
  "country": "US",
  "currency": "usd",
  "fingerprint": "1JWtPxqbdX5Gamtc",
  "id": "ba_1B3xSU2eZvKYlo2CDAgYCVfe",
  "last4": "6789",
  "metadata": {},
  "object": "bank_account",
  "routing_number": "110000000",
  "status": "new"
}`

Even when I try with /cards. I don't know which one is correct because in stripe-go it is /cards but in the stripe api docs it is /sources.

**Comment by brandur-stripe** [comment]
Hi @ruzaikr, sorry about the trouble here!

Unfortunately, this is a current limitation of `stripe-mock`. Basically it's designed to return some kind of response for any given endpoint that's known to be accurate, but it doesn't necessarily reflect anything that came in via input.

As a simple example, if you create a charge with `amount` of `123`, the resource you get back probably won't have `123` as an amount. A more complex example are sources, where the type is often wrong.

We want to get this fixed, but it'll require adding a fair bit of intelligence to `stripe-mock` around how some of the Stripe domain logic actually works — currently it's fairly dumbly just following along according to an integrated OpenAPI spec.

**Comment by dja** [comment]
@brandur-stripe Any updates on this yet? 🙇

**Comment by benoj** [comment]
Same issue here  ☹️

**Comment by zachfeldman** [comment]
Just leaving this here in case it's helpful to anyone using Rspec that comes across this:

```
Stripe::Customer.stub_chain(:retrieve, :sources, :all).and_return(OpenStruct.new({
    data: [
      OpenStruct.new({
        brand: "Visa",
        exp_month: 10,
        exp_year: 2019,
        last4: 4242,
        id: 3245644343
      })
    ]
  }))
```

This solved my issue with bank accounts vs credit cards.

**Comment by jmarcoscosta2015** [comment]
i'm having this issue now. Any updates yet?

**Comment by remi-stripe** [comment]
@jmarcoscosta2015 unfortunately no update. This is a legacy API from when we could return different API Resources. This is a pattern that we do not have in newer APIs anymore and so we likely won't fix this on stripe-mock. We recommend using the newer APIs so `PaymentMethod` instead of `Card`. Unfortunately for ACH support it's still only on `BankAccount` but we are working on porting this to `PaymentMethod`.

**Comment by anniel-stripe** [comment]
Hello, sorry for the late update here! Closing this as out of scope because, as mentioned above, we will likely not be fixing this issue for this legacy API. You can refer to [our README](https://github.com/stripe/stripe-mock#future-plans) for more details about future plans for stripe-mock.
