### ISSUE TITLE
Support sending webhooks

### ISSUE THREAD

**Issue by boatcoder** [stripe/stripe-mock#369]
We react to a lot of webhooks that are generated by making API calls.  Checkout => Checkout Complete => Invoice Paid. Webhooks appear to be completely ignored and yet we get MOST of our data from them.

**Comment by kamil-stripe** [comment]
Hi @boatcoder! Thank you for your report. `stripe-mock` is designed to support API calls only. To simulate a webhook event, we recommend using Stripe CLI and `stripe trigger` command. You can read more at https://stripe.com/docs/webhooks/test#webhook-test-cli. Feel free to reach out in case of any questions.
