### ISSUE TITLE
Create Subscription Schedule returns sub ID incorrectly 

### ISSUE THREAD

**Issue by davidhough** [stripe/stripe-mock#376]
When creating a subscription schedule, the underlying subscription's ID should be returned in the `subscription` field of the response. A subscription schedule ID is returned in the `id` field. Subscription schedule IDs are prefixed with `sub_sched` whereas subscription IDs are prefixed with just `sub` to disambiguate. This is the current response from stripe-mock:
```
{
  "application": null,
  "canceled_at": 1234567890,
  "completed_at": 1234567890,
  "created": 1234567890,
  "current_phase": null,
  "customer": "esse ut",
  "default_settings": {
    "application_fee_percent": null,
    "automatic_tax": {
      "enabled": false
    },
    "billing_cycle_anchor": "automatic",
    "billing_thresholds": null,
    "collection_method": "charge_automatically",
    "default_payment_method": null,
    "description": null,
    "invoice_settings": null,
    "transfer_data": null
  },
  "end_behavior": "release",
  "id": "sub_JpBZ3b9wsZpgsxT",
  "livemode": false,
  "metadata": {},
  "object": "subscription_schedule",
  "phases": [
    {
      "add_invoice_items": [],
      "application_fee_percent": null,
      "automatic_tax": null,
      "billing_cycle_anchor": null,
      "billing_thresholds": null,
      "collection_method": null,
      "coupon": null,
      "currency": null,
      "default_payment_method": null,
      "default_tax_rates": [],
      "description": null,
      "end_date": 1693583297,
      "invoice_settings": null,
      "items": [
        {
          "billing_thresholds": null,
          "plan": null,
          "price": "price_1Lb4lXDciZwYG8GPenVxKLUQ",
          "quantity": 1,
          "tax_rates": []
        }
      ],
      "metadata": {},
      "proration_behavior": "create_prorations",
      "start_date": 1662133697,
      "transfer_data": null,
      "trial_end": null
    }
  ],
  "released_at": 1234567890,
  "released_subscription": null,
  "status": "not_started",
  "subscription": null,
  "test_clock": null
}
```

Currently the `subscription` field is `null`, it should return `"sub_JpBZ3b9wsZpgsxT"`.
The `id` field is `sub_JpBZ3b9wsZpgsxT`, it should return a different ID prefixed with `sub_sched`.

**Comment by pakrym-stripe** [comment]
Hi @davidhough, thank you for the feedback. 

We fixed the id prefix issue in https://github.com/stripe/stripe-mock/pull/377 and it's now available in the latest version of `stripe-mock`.

Unfortunately stripe-mock is not stateful and doesn't carry any logic so we can only have one hardcoded response for each endpoint. The one we currently have represents a `subscription_schedule` that will start in the future so it doesn't have a `subscription_id`.

There are already some open feature requests for making stripe-mock more stateful, such as https://github.com/stripe/stripe-mock/issues/19 and https://github.com/stripe/stripe-mock/issues/52, so I'm going to close this issue.
