### ISSUE TITLE
CORS Issue with the official stripe node library

### ISSUE THREAD

**Issue by src-r-r** [stripe/stripe-mock#412]
Simple example:
```ts
import Stripe from "stripe";
import { STRIPE_API_KEY, STRIPE_NETWORK_CONFIG } from "~/lib/common"
import axios from "axios";


export const stripe = new Stripe(STRIPE_API_KEY, {
    apiVersion: "2022-11-15",
    port: "12111",
    host: "localhost",
    protocol: "http",
});

// later on...
await stripe.customers.create({});
```

This results in the following response:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:12111/v1/customers. (Reason: CORS request did not succeed). Status code: (null).
```

I'm attempting to fix it by adding headers to the response in `server/server.go`

```go
// Set CORS headers
w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
w.Header().Set("Access-Control-Allow-Headers", "*")
w.Header().Set("Referrer-Policy", "strict-origin-when-cross-origin")
```

However, I'm still getting the same response.

Could this be an issue with the node stripe client?

# Edit - Updated Info

It is an issue with the stripe client, but more of a "feature" that's causing an issue.

The stripe client first sends an `OPTION` request. If you send a request `OPTIONS http://localhost:12111/v1/customers` with the header `Bearer sk_test_123` the following response comes back:

```json
{
    "error": {
        "message": "Unrecognized request URL (OPTIONS: /v1/customers).",
        "type": "invalid_request_error"
    }
}
```

However, if you do a POST using the same info:

```json
{
    "address": null,
    "balance": 0,
    "created": 1234567890,
    "currency": "usd",
    "default_source": null,
    // ...
}
```

And looks like the `method_type` is not found in the customer routes:

```json
        "x-stripeOperations": [
          {
            "method_name": "update",
            "method_on": "service",
            "method_type": "update",
            "operation": "post",
            "path": "/v1/customers/{customer}/sources/{id}"
          },
          {
            "method_name": "delete",
            "method_on": "service",
            "method_type": "delete",
            "operation": "delete",
            "path": "/v1/customers/{customer}/sources/{id}"
          },
          {
            "method_name": "verify",
            "method_on": "service",
            "method_type": "custom",
            "operation": "post",
            "path": "/v1/customers/{customer}/sources/{id}/verify"
          },
          {
            "method_name": "update",
            "method_on": "service",
            "method_type": "update",
            "operation": "post",
            "path": "/v1/accounts/{account}/external_accounts/{id}"
          },
          {
            "method_name": "delete",
            "method_on": "service",
            "method_type": "delete",
            "operation": "delete",
            "path": "/v1/accounts/{account}/external_accounts/{id}"
          }
        ],
```

So then I think a good fix (that I'm working on) would be to create an OPTIONS stub for any path.

**Comment by anniel-stripe** [comment]
Hi, thanks for submitting this issue! 

I wasn't able to recreate the CORS issue using the example you gave above, and was able to send requests to stripe-mock with the latest version of stripe-node. The stripe-node client doesn't send an `OPTIONS` request first - this seems to be a quirk of axios / CORS policy (see [related SO post](https://stackoverflow.com/questions/70473973/disable-options-request-before-post-and-delete-requests)).

We could handle `OPTIONS` requests directly in stripe-mock like the SO post suggests, but given that sending an `OPTIONS` request is not a feature of the official Stripe client libraries and [stripe-mock is in maintenance mode](https://github.com/stripe/stripe-mock#future-plans) and there haven't been previous reports opened in stripe-mock for this issue, we're unlikely to prioritize this.

**Comment by anniel-stripe** [comment]
If you would like to open a pull request that emulates how the Stripe API responds to `OPTIONS` requests, could you explain more about your use case? We're surprised to see that you had sent requests with the `OPTIONS` method type, but given that the real Stripe API responds to `OPTIONS` requests without error, we're open to merging a PR into stripe-mock for this.

**Comment by richardm-stripe** [comment]
Closing from inactivity. Feel free to re-open if you can detail your use case!
