### ISSUE TITLE
Use `verbose` flag for printing request data and response time

### ISSUE THREAD

**Issue by josejibin** [stripe/stripe-mock#416]
Hi Team, 

Thanks for this project. 

Wondering if we can put printing of[ request data](https://github.com/stripe/stripe-mock/blob/master/server/server.go#L231) and[ response time](https://github.com/stripe/stripe-mock/blob/master/server/server.go#L927) behind the verbose flag?

This will help us to reduce the noise while testing.

I have submitted a [PR](https://github.com/stripe/stripe-mock/pull/417) request for the same. 

Please feel free to close this if this is not a good idea.

**Comment by pakrym-stripe** [comment]
Hi @josejibin, your request makes sense but we limit `stripe-mock` development to bug fixes only.
