### ISSUE TITLE
Update README with 'go install' instructions

### ISSUE THREAD

**Issue by priyanshujain** [stripe/stripe-mock#436]
I would like to suggest an improvement to the installation instructions in the README of the Stripe-Mock repository. Currently, the README suggests installing the package using the command 'go get', but I believe it would be more consistent and convenient to use 'go install' instead.

Here are the reasons for my suggestion:
1. Uniformity: Many Go packages recommend using 'go install' for installation, which is the standard way of installing Go binaries.
2. Simplicity: 'go install' downloads and installs the package in a single step, without the need for additional commands.
3. Reduced clutter: 'go install' places the binary in the default location, which is typically in the user's $GOPATH/bin directory. This avoids adding additional dependencies to the project.

I propose updating the README with the following installation instructions:

```shell
go install github.com/stripe/stripe-mock
```

I believe this change would enhance the user experience and align the installation process with the Go community's conventions. Thank you for considering my suggestion.

**Comment by anniel-stripe** [comment]
Hi @priyanshujain , very happy to take your suggestion, and thanks for providing a detailed list of reason! Do you want to open a PR to update the README? Should just be a one-line change, and that way you can get direct credit for the contribution. :)

**Comment by priyanshujain** [comment]
@anniel-stripe I have raised the PR (#437).
