### ISSUE TITLE
PaymentIntent status "requires_payment_method" when payment_method is present

### ISSUE THREAD

**Issue by adamthehutt** [stripe/stripe-mock#473]
I have a test case that's providing "pm_card_visa" as the payment_method parameter when creating a payment intent. This code has worked fine for years, but for some reason with a fresh install of stripe-mock, I'm now getting a payment intent with the status "requires_payment_method" (which our code treats as a failed charge attempt). The object has the payment property (set to "pm_card_visa") so I'm not sure why this would be happening.

**Comment by pakrym-stripe** [comment]
Hi @adamthehutt, 

stripe-mock does not attempt to reproduce the behavior of the real Stripe API at all and uses canned responses that are shared with Stripe API ref. Unfortunately there is no guarantee that responses will make sense in regards to the requests being sent or that responses won't change.

We recommend using your language's mocking framework to set up exact responses your application needs for validation.
