### ISSUE TITLE
Publish docker image to docker hub?

### ISSUE THREAD

**Issue by mmmmmrob** [stripe/stripe-mock#49]
Is there an official build of the docker image that can be used without building? I couldn't find one on docker hub.

**Comment by brandur** [comment]
I added #50 to push an image to Docker Hub based off the `master` branch (we might do tagged images at some point in the future too, but we'll do the easy thing for now).

A couple caveats:

1. For now this is being built to https://hub.docker.com/r/stripemock/stripe-mock/, but we'll probably move the repository shortly to `stripe/stripe-mock`, so keep an eye out for that.
2. The image is large (~91 MB) right now. #51 should be coming in soon, which will lean it out quite a bit.
