### ISSUE TITLE
Implementation with stripe terminal on android for android instrumental tests

### ISSUE THREAD

**Issue by tom42530** [stripe/stripe-mock#534]
Hi,

It is possible to use with stripe-terminal sdk?

i don't find any mention in stripe terminal sdk how to customize api domain/port to mock stripe api call
Instrumental tests on isolated device without internet connection

Thanks in advance

**Comment by remi-stripe** [comment]
@tom42530 I don't think there's any way to instrument our Terminal SDKs today to hit stripe-mock I'm sorry. Could be a good feature request that you could port to https://github.com/stripe/stripe-terminal-ios but it's unlikely to be built soon unfortunately.
I'm going to close this out as it's not really a question about stripe-mock itself, hope it's okay!
