### ISSUE TITLE
How to integrations-test a java application via stripe-mock

### ISSUE THREAD

**Issue by hjoly2003** [stripe/stripe-mock#590]
Hi, I want to use *stripe-mock* for the *integration tests* of our java server. How can I configure this so that our calls to the *spripe-java API* get served by *stripe-mock*?

Someone from [Discord stripe-help](https://discord.com/channels/841573134531821608/841573134531821616) suggested to override the value of `Stripe::LIVE_API_BASE` with your suggested URL (http://localhost:12111). Its is the thing to do?

Thanks in advance

**Comment by remi-stripe** [comment]
@hjoly2003 Github issues are limited to bugs or feature requests with the library and this is more an integration support question better directed at our support team: https://support.stripe.com/contact

To unblock you though I can confirm this is the right path forward. I'd recommend looking at how we do this in the test suite of our stripe-java SDK where we rely on stripe-mock. You can see [here](https://github.com/stripe/stripe-java/blob/fe60750ed3e284311056d4ad9912e1a294b6f0ff/src/test/java/com/stripe/BaseStripeTest.java#L109) for example how we configure the SDK to use the local instance of stripe-mock.

If you have follow up questions please contact our support team: https://support.stripe.com/contact
