### ISSUE TITLE
Reflect an object's primary ID from a path back in the response

### ISSUE THREAD

**Issue by ob-stripe** [stripe/stripe-mock#61]
#59 implemented this feature, but there are a few cases in which it doesn't work:

- non-CRUD methods:
    - `POST /v1/accounts/<ID>/reject`
    - `POST /v1/application_fees/<ID>/refund`
    - `POST /v1/charges/<ID>/capture`
    - `POST /v1/charges/<ID>/refund`
    - `POST /v1/payouts/<ID>/cancel`
    - `POST /v1/sources/<ID>/verify`

- nested resources:
    - `POST /v1/application_fees/<FEE_ID>/refunds/<FEE_REFUND_ID>`: this returns an `application_fee` with `id=<FEE_REFUND_ID>`, but the `fee` attribute is that of the fixture (`fee_1CDJmvCLWM6HLS3K5kilrl2R`) instead of `<FEE_ID>`

**Comment by brandur-stripe** [comment]
Haha, you are the best alpha tester ever OB!

Okay, I put in a list of special cases already so it'll be easy to get that first list to work at least (I'll open a PR soon).

I think I have an answer for the second too, but unfortunately it'll be a little longer coming — it'll require a more elegant approach to parsing query parameters based off better information in OpenAPI. I'm planning on working on that this week.

**Comment by brandur-stripe** [comment]
Put together the first part of this fix in #62.

**Comment by remi-stripe** [comment]
Lurking in: we should look into expand (and whether we want to fix it there too) as you can end up expanding back to the root object and would need to properly change the ids for those sub-resources too.

**Comment by brandur-stripe** [comment]
@remi-stripe Yeah, it at least _tries_ to support that already by recursing all the way into every generated object and changing values around, but I wouldn't be too surprised if there were some failing edge cases. I'll keep an eye on trying to improve that for the next version.

**Comment by brandur-stripe** [comment]
Okay, subresources are now handled too! (Available in 0.14.0.) Closing this out.
