### ISSUE TITLE
Account Link is not working with additional Parameters

### ISSUE THREAD

**Issue by Baravd** [stripe/stripe-mock#641]
Hello,

I'm encountering an issue when calling :` AccountLink.create(accountLinkCreateParams);`

in the params we add the following params which are required by some US regulations change on stripe sides for connected accounts:
`.putExtraParam("collection_options[fields]", AccountLinkCreateParams.Collect.EVENTUALLY_DUE)
                .putExtraParam("collection_options[future_requirements]", "include")`

We have connected accounts on our stripe integration
The error I receive is:  com.stripe.exception.InvalidRequestException: Request validation error: validator 0xc000ccefc0 failed: additional properties are not allowed; request-id: req_123

`<com.stripe.model.StripeError@27496340 id=> JSON: {
  "charge": null,
  "code": null,
  "decline_code": null,
  "doc_url": null,
  "message": "Request validation error: validator 0xc000ccefc0 failed: additional properties are not allowed",
  "param": null,
  "payment_intent": null,
  "payment_method": null,
  "payment_method_type": null,
  "request_log_url": null,
  "setup_intent": null,
  "source": null,
  "type": "invalid_request_error"
}`

Without these two extra params, the call works, but obviously in production it works with these params too.

**Comment by remi-stripe** [comment]
@Baravd This is an integration support question and should be directed to our support team for 1:1 help instead of on a public Github issue. Please contact them here https://support.stripe.com/contact and they will be able to help you debug this.
