### ISSUE TITLE
Can we cut a new release?

### ISSUE THREAD

**Issue by danieljnchen** [stripe/stripe-mock#767]
There are some changes since v0.184.0, notably the `create_preview` endpoint, that it would be nice to have accessible.

**Comment by anniel-stripe** [comment]
Hi there! Sorry about that, just cut a new release in [v0.185.0](https://github.com/stripe/stripe-mock/releases/tag/v0.185.0) that contains the `create_preview` endpoint

**Comment by danieljnchen** [comment]
Thank you, much appreciated!
