### ISSUE TITLE
Add healthcheck endpoint

### ISSUE THREAD

**Issue by krystof-k** [stripe/stripe-mock#768]
It would be great to have the [`/healthcheck`](https://api.stripe.com/healthcheck) endpoint available also in the mock:

```
Stripe API mock at your service! What can I do for you today?
```

**Comment by anniel-stripe** [comment]
Hi @krystof-k , thanks for the feature request. Unfortunately, we won't be prioritizing this for the following reasons:
1. `/healthcheck` is not in [Stripe’s OpenAPI specification](https://github.com/stripe/openapi) as a publicly documented endpoint. It is not supported the official Stripe client libraries or mentioned in the documentation.
1.  [stripe-mock is in maintenance mode](https://github.com/stripe/stripe-mock#future-plans), and we are not expanding its functionality beyond keeping it up to date with the latest spec / bug fixes at the moment.
1. If you’d like to verify that stripe-mock is up and running, you can do so by sending a request to an arbitrary endpoint. This is what we do in the client libraries.

**Comment by krystof-k** [comment]
Hi @anniel-stripe, thanks for your response. It's a pity but I understand.
