### ISSUE TITLE
Customer#default_source not present in response

### ISSUE THREAD

**Issue by carlesjove** [stripe/stripe-mock#78]
Hi,

I'm having this issue testing in Ruby, using stripe-mock, in which `stripe_customer.default_source` raises a `NoMethodError`. I'm afraid this is because responses from stripe-mock don't include this attribute.

**Comment by brandur-stripe** [comment]
As mentioned in stripe/openapi#34, I'll see if I can add a patch for this on the server.

**Comment by brandur-stripe** [comment]
I just released a new version in 0.18.0 where this issue should now be addressed.

**Comment by carlesjove** [comment]
@brandur-stripe Thanks!
