### ISSUE TITLE
List endpoints should support `limit` parameter

### ISSUE THREAD

**Issue by remi-stripe** [stripe/stripe-mock#81]
When you use one of the List APIs and pass `limit`, the parameter is ignored and the returned list only contains one object. It would be great if it supported returning more than 1.

**Comment by brandur-stripe** [comment]
+1 million. I think this would be a great enhancement after we have #19 implemented (so that it's possible to have a little more data to actually return on list endpoints). Marking as future for now, but I'm very much hoping to get around to a few of these improvements soon.

**Comment by anniel-stripe** [comment]
Closing as we're unlikely to prioritize
